Latihan Review Code
Fulanah06/BerajarLagi pull request #4
Opened 2023-09-20 13:22 UTC by Stnurhalima

Belajar Melakukan code Review

2023-09-20 13:36 UTC, Fulanah06 reviewed
Tanda Heding satunya (--)di hapus aja karnaitu berlaku untuk file README.md

2023-09-20 13:45 UTC, Fulanah06 requested changes
Tanda Heding satunya (--)di hapus aja karnaitu berlaku untuk file README.md

2023-09-20 13:45 UTC, Fulanah06 commented on Latihan Review Code
> +--
Hapus aja tanda yang ini

2023-09-20 14:13 UTC, Stnurhalima commented on Latihan Review Code
> +--
perubahan diterima

2023-09-22 23:21 UTC, closed without merging

2023-09-22 23:45 UTC, Fulanah06 commented
okw